export const currentUser = {
  name: "",
  handle: "",
  avatar: "",
  role: "student" as "student" | "tutor" | "admin",
  credits: 100,
  streak: 0,
  university: "",
  major: "",
  year: "",
  country: "",
  timezone: "",
  languages: [] as string[],
  bio: "",
  goals: [] as string[],
  weeklyHours: 0,
  dailyGoalMin: 60,
  todayMin: 0,
};

export const tutors = [
  {
    id: "t1",
    name: "Dr. Sana Rehman",
    handle: "dr_sana",
    subject: "Machine Learning",
    university: "Stanford",
    rating: 4.9,
    sessions: 214,
    credits: 60,
    lang: "English",
    tz: "PST",
    avatar: "https://i.pravatar.cc/150?img=47",
    tags: ["Deep Learning", "PyTorch", "Transformers"],
    why: "Matches your weak topic in backprop and shares your evening timezone.",
  },
  {
    id: "t2",
    name: "Ken Watanabe",
    handle: "ken_watanabe",
    subject: "Operating Systems",
    university: "U. Tokyo",
    rating: 4.8,
    sessions: 189,
    credits: 45,
    lang: "English",
    tz: "JST",
    avatar: "https://i.pravatar.cc/150?img=15",
    tags: ["Deadlocks", "Kernel", "Concurrency"],
    why: "You bookmarked 3 OS threads he answered this week.",
  },
  {
    id: "t3",
    name: "Maria Alvarez",
    handle: "maria_alvarez",
    subject: "Data Structures",
    university: "MIT",
    rating: 5.0,
    sessions: 302,
    credits: 70,
    lang: "Spanish/English",
    tz: "EST",
    avatar: "https://i.pravatar.cc/150?img=45",
    tags: ["Graphs", "DP", "Interview Prep"],
    why: "Top rated tutor for your midterm topic.",
  },
  {
    id: "t4",
    name: "Ibrahim Diallo",
    handle: "ibrahim_diallo",
    subject: "Linear Algebra",
    university: "ETH Zürich",
    rating: 4.7,
    sessions: 121,
    credits: 40,
    lang: "English/French",
    tz: "CET",
    avatar: "https://i.pravatar.cc/150?img=68",
    tags: ["Eigenvectors", "SVD"],
    why: "High compatibility score based on your learning pace.",
  },
  {
    id: "t5",
    name: "Priya Nair",
    handle: "priya_nair",
    subject: "Databases",
    university: "IIT Madras",
    rating: 4.9,
    sessions: 176,
    credits: 50,
    lang: "English/Hindi",
    tz: "IST",
    avatar: "https://i.pravatar.cc/150?img=32",
    tags: ["SQL", "Indexing", "Sharding"],
    why: "Same university, same year — pairs well with your schedule.",
  },
  {
    id: "t6",
    name: "Lucas Meier",
    handle: "lucas_meier",
    subject: "Algorithms",
    university: "TU Munich",
    rating: 4.8,
    sessions: 143,
    credits: 55,
    lang: "English/German",
    tz: "CET",
    avatar: "https://i.pravatar.cc/150?img=59",
    tags: ["Greedy", "DP", "Graphs"],
    why: "Complements your weekly plan for competitive programming.",
  },
];

export const buddies = [
  {
    id: "b1",
    name: "Aditi Sharma",
    topic: "Data Structures Midterm",
    exam: "Nov 30",
    uni: "IIT Delhi",
    tz: "IST",
    avatar: "https://i.pravatar.cc/150?img=25",
    match: 94,
  },
  {
    id: "b2",
    name: "Chen Wei",
    topic: "Machine Learning Practice",
    exam: "Ongoing",
    uni: "Tsinghua",
    tz: "CST",
    avatar: "https://i.pravatar.cc/150?img=11",
    match: 88,
  },
  {
    id: "b3",
    name: "Fatima Zahra",
    topic: "IELTS Preparation",
    exam: "Dec 12",
    uni: "Cairo U.",
    tz: "EET",
    avatar: "https://i.pravatar.cc/150?img=44",
    match: 82,
  },
  {
    id: "b4",
    name: "Diego Ramos",
    topic: "React & Next.js",
    exam: "Ongoing",
    uni: "UNAM",
    tz: "CST",
    avatar: "https://i.pravatar.cc/150?img=57",
    match: 79,
  },
];

export const sosRequests = [
  {
    id: "s1",
    title: "OS exam tomorrow — Deadlocks help!",
    subject: "Operating Systems",
    urgency: "High",
    credits: 80,
    duration: "45m",
    lang: "English",
    author: "Nia K.",
    avatar: "https://i.pravatar.cc/150?img=20",
    status: "Open",
    posted: "12m ago",
    offers: 4,
  },
  {
    id: "s2",
    title: "Networking quiz starts in 1 hour",
    subject: "Computer Networks",
    urgency: "Critical",
    credits: 120,
    duration: "30m",
    lang: "English",
    author: "Rahul S.",
    avatar: "https://i.pravatar.cc/150?img=33",
    status: "Matched",
    posted: "24m ago",
    offers: 7,
  },
  {
    id: "s3",
    title: "ML assignment due tonight — SVM intuition",
    subject: "Machine Learning",
    urgency: "Medium",
    credits: 60,
    duration: "60m",
    lang: "English",
    author: "Sara M.",
    avatar: "https://i.pravatar.cc/150?img=48",
    status: "Open",
    posted: "1h ago",
    offers: 2,
  },
  {
    id: "s4",
    title: "Understanding pointer arithmetic in C",
    subject: "Systems Programming",
    urgency: "Low",
    credits: 30,
    duration: "20m",
    lang: "English",
    author: "Kwame O.",
    avatar: "https://i.pravatar.cc/150?img=51",
    status: "Open",
    posted: "2h ago",
    offers: 1,
  },
];

export const posts = [
  {
    id: "p1",
    author: "Elena Rossi",
    avatar: "https://i.pravatar.cc/150?img=41",
    time: "2h",
    subject: "Algorithms",
    title: "A visual intuition for Dijkstra vs A*",
    body: "Sharing my hand-drawn notes that finally made this click. What tricks helped you?",
    likes: 214,
    comments: 38,
    tag: "Notes",
  },
  {
    id: "p2",
    author: "James Park",
    avatar: "https://i.pravatar.cc/150?img=12",
    time: "5h",
    subject: "Machine Learning",
    title: "Why do transformers scale better than LSTMs?",
    body: "Trying to explain this to my study group. Looking for concrete intuitions beyond 'attention is all you need'.",
    likes: 172,
    comments: 54,
    tag: "Question",
  },
  {
    id: "p3",
    author: "Ana Beatriz",
    avatar: "https://i.pravatar.cc/150?img=36",
    time: "1d",
    subject: "Databases",
    title: "Free 40-page PDF: Indexing Deep Dive",
    body: "Compiled from Andy Pavlo's lectures + my notes. Enjoy 🙌",
    likes: 431,
    comments: 89,
    tag: "Resource",
  },
];

export const groups = [
  {
    id: "g1",
    name: "Distributed Systems Fall '25",
    members: 24,
    subject: "Distributed Systems",
    active: "3 online",
    color: "from-violet-500 to-fuchsia-500",
  },
  {
    id: "g2",
    name: "LeetCode Grind — Daily",
    members: 118,
    subject: "Algorithms",
    active: "12 online",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "g3",
    name: "IELTS Speaking Circle",
    members: 42,
    subject: "English",
    active: "5 online",
    color: "from-amber-500 to-orange-500",
  },
  {
    id: "g4",
    name: "ML Paper Reading Club",
    members: 67,
    subject: "Machine Learning",
    active: "9 online",
    color: "from-emerald-500 to-teal-500",
  },
];

export const messages = [
  {
    id: "m1",
    name: "Aditi Sharma",
    last: "Sending the DP cheatsheet now!",
    time: "2m",
    unread: 2,
    avatar: "https://i.pravatar.cc/150?img=25",
    online: true,
  },
  {
    id: "m2",
    name: "Dr. Sana Rehman",
    last: "Great, see you at 7 PM your time.",
    time: "1h",
    unread: 0,
    avatar: "https://i.pravatar.cc/150?img=47",
    online: true,
  },
  {
    id: "m3",
    name: "ML Paper Reading Club",
    last: "Chen: Section 3 is wild.",
    time: "3h",
    unread: 5,
    avatar: "https://i.pravatar.cc/150?img=11",
    online: false,
  },
  {
    id: "m4",
    name: "Ken Watanabe",
    last: "Try this diagram for deadlocks.",
    time: "1d",
    unread: 0,
    avatar: "https://i.pravatar.cc/150?img=15",
    online: false,
  },
];

export const notifications = [
  {
    id: "n1",
    type: "credit",
    text: "You earned 45 credits for helping Nia with Deadlocks.",
    time: "12m",
  },
  { id: "n2", type: "sos", text: "3 new SOS requests match your teaching subjects.", time: "40m" },
  {
    id: "n3",
    type: "buddy",
    text: "Aditi Sharma invited you to a private study room.",
    time: "2h",
  },
  {
    id: "n4",
    type: "achievement",
    text: "Achievement unlocked: 7-day study streak 🔥",
    time: "1d",
  },
  {
    id: "n5",
    type: "session",
    text: "Session with Dr. Sana Rehman starts in 30 minutes.",
    time: "1d",
  },
];

export const leaderboard = [
  {
    rank: 1,
    name: "Maria Alvarez",
    credits: 8432,
    hours: 214,
    avatar: "https://i.pravatar.cc/150?img=45",
    badge: "Legend",
  },
  {
    rank: 2,
    name: "Ken Watanabe",
    credits: 7120,
    hours: 189,
    avatar: "https://i.pravatar.cc/150?img=15",
    badge: "Top Mentor",
  },
  {
    rank: 3,
    name: "Priya Nair",
    credits: 6884,
    hours: 176,
    avatar: "https://i.pravatar.cc/150?img=32",
    badge: "Rising Star",
  },
  {
    rank: 4,
    name: "Lucas Meier",
    credits: 5341,
    hours: 143,
    avatar: "https://i.pravatar.cc/150?img=59",
    badge: "Consistent",
  },
  {
    rank: 5,
    name: "Elena Rossi",
    credits: 4720,
    hours: 121,
    avatar: "https://i.pravatar.cc/150?img=41",
    badge: "Community Hero",
  },
  {
    rank: 12,
    name: "Aarav Mehta (You)",
    credits: 1240,
    hours: 42,
    avatar: "https://i.pravatar.cc/150?img=13",
    badge: "Learner",
  },
];

export const achievements = [
  { id: "a1", name: "First Steps", desc: "Complete onboarding", earned: true, icon: "Sparkles" },
  { id: "a2", name: "Study Streak", desc: "7 days in a row", earned: true, icon: "Flame" },
  { id: "a3", name: "Community Hero", desc: "10 accepted answers", earned: true, icon: "Heart" },
  { id: "a4", name: "Quiz Master", desc: "Score 100% on 5 quizzes", earned: false, icon: "Trophy" },
  {
    id: "a5",
    name: "Top Tutor",
    desc: "50 sessions with 4.8+",
    earned: false,
    icon: "GraduationCap",
  },
  { id: "a6", name: "Fast Responder", desc: "Answer SOS in <5min", earned: true, icon: "Zap" },
  { id: "a7", name: "100 Hours Teaching", desc: "Cumulative", earned: false, icon: "Clock" },
  {
    id: "a8",
    name: "Excellent Mentor",
    desc: "20+ five-star ratings",
    earned: false,
    icon: "Star",
  },
];

export const quizzes = [
  {
    id: "q1",
    title: "Deadlocks & Semaphores",
    subject: "Operating Systems",
    questions: 12,
    difficulty: "Medium",
    ai: true,
  },
  {
    id: "q2",
    title: "Big-O Sprint",
    subject: "Algorithms",
    questions: 20,
    difficulty: "Easy",
    ai: true,
  },
  {
    id: "q3",
    title: "SQL Joins Deep Dive",
    subject: "Databases",
    questions: 15,
    difficulty: "Hard",
    ai: false,
  },
  {
    id: "q4",
    title: "React Hooks Essentials",
    subject: "Frontend",
    questions: 10,
    difficulty: "Easy",
    ai: true,
  },
];

export const roadmaps = [
  {
    id: "r1",
    title: "Machine Learning from Zero",
    weeks: 12,
    progress: 34,
    milestones: 24,
    color: "from-violet-500 to-fuchsia-500",
  },
  {
    id: "r2",
    title: "System Design Interview",
    weeks: 8,
    progress: 62,
    milestones: 18,
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "r3",
    title: "Full-Stack with Next.js",
    weeks: 10,
    progress: 12,
    milestones: 22,
    color: "from-emerald-500 to-teal-500",
  },
];

export const aiTools = [
  {
    id: "study",
    name: "Study Assistant",
    desc: "Ask anything, get grounded answers with sources.",
    icon: "Sparkles",
  },
  {
    id: "lecture",
    name: "Lecture Generator",
    desc: "Turn a topic into a 30-min structured lecture.",
    icon: "GraduationCap",
  },
  {
    id: "pdf",
    name: "PDF Analysis",
    desc: "Upload notes or papers, get summaries & key ideas.",
    icon: "FileText",
  },
  {
    id: "flash",
    name: "Flashcards",
    desc: "Auto-generate spaced-repetition decks.",
    icon: "Layers",
  },
  {
    id: "mind",
    name: "Mind Maps",
    desc: "Visualize concepts and their connections.",
    icon: "Network",
  },
  {
    id: "quiz",
    name: "Quiz Generator",
    desc: "Create adaptive quizzes from any material.",
    icon: "ListChecks",
  },
  {
    id: "weak",
    name: "Weakness Analysis",
    desc: "Identify blind spots based on your history.",
    icon: "Target",
  },
  {
    id: "plan",
    name: "Study Planner",
    desc: "Build a weekly plan aligned to your exams.",
    icon: "CalendarClock",
  },
  {
    id: "road",
    name: "Roadmap Generator",
    desc: "Design a multi-week curriculum for any skill.",
    icon: "Map",
  },
  {
    id: "rec",
    name: "Tutor Recommendation",
    desc: "Find the right human, explained.",
    icon: "UserCheck",
  },
  {
    id: "hw",
    name: "Homework Guidance",
    desc: "Hints without spoilers — learn, don't cheat.",
    icon: "HelpCircle",
  },
  {
    id: "code",
    name: "Coding Assistant",
    desc: "Debug, review, explain — all languages.",
    icon: "Code2",
  },
  {
    id: "mock",
    name: "Mock Interview",
    desc: "Practice technical & behavioral rounds.",
    icon: "Mic",
  },
  {
    id: "exam",
    name: "Exam Preparation",
    desc: "Predictive prep with past-paper analysis.",
    icon: "BookOpen",
  },
];

export const upcomingExams = [
  { subject: "Distributed Systems", date: "Dec 4", daysLeft: 6, readiness: 62 },
  { subject: "Machine Learning", date: "Dec 11", daysLeft: 13, readiness: 41 },
  { subject: "Databases", date: "Dec 18", daysLeft: 20, readiness: 78 },
];

export const creditsHistory = [
  { id: "c1", type: "earn", amount: 45, reason: "SOS help — Deadlocks", time: "12m" },
  { id: "c2", type: "spend", amount: -60, reason: "Session with Dr. Sana Rehman", time: "2h" },
  { id: "c3", type: "earn", amount: 20, reason: "Accepted community answer", time: "5h" },
  { id: "c4", type: "earn", amount: 10, reason: "Daily streak bonus", time: "1d" },
  { id: "c5", type: "spend", amount: -25, reason: "AI PDF Analysis (premium)", time: "1d" },
  { id: "c6", type: "earn", amount: 80, reason: "Uploaded resource (312 downloads)", time: "3d" },
];
